// Updated: C4 diagram, textarea+modal (#20), Skeleton for streaming (#22), ConfirmDialog overlay (#23), type `WidgetRegistry` renamed to `WidgetMap` to free the name for the runtime class in core/widget-registry.ts
// Updated 2026-05-22: registered the `media/` escape-hatch widgets — ModelViewer (declarative 3D, type `model-viewer`/`3d`/`model`) and Embed (sandboxed iframe, type `embed`/`iframe`) for Increment 5.
// Updated 2026-05-30: registered the `motion/` sugar widgets — Reveal (type `reveal`) and Parallax (type `parallax`), which desugar to a motion field (RFC 12 animation primitive).
// Updated 2026-05-30: registered the `marketing/` widget pack — Navbar, Footer, Cta, Testimonial, FeatureGrid, Newsletter, LogoCloud (+ aliases) for the RFC 12 landing-page pack (Phase 3).
import type { Component } from 'svelte';

import { Container, Flex, Grid, Card, GlassCard, Tabs, Dashboard, DashboardSlot, Modal, Accordion, Sheet, Separator, PageHeader, Hero, Section, Sidebar, AppShell, Breadcrumb, Split, MasterDetail, Collapsible } from './layout/index.js';
import { Text, Heading, Image, Badge, Progress, Avatar, Metric, Stat, SoulStatus, Skeleton, Markdown, CodeBlock, EmptyState, ProsCons, ComparisonTable, Steps, Quote, Highlight, DefinitionList, ArticleMeta, Icon, Loading, Chip, Kbd, StatusDot, Trend, Copy, Code, ProgressRing, Mention, LinkPreview, Qr, Diff } from './display/index.js';
import { Button, Input, Select, Checkbox, Switch, Textarea, Slider, RadioGroup, Rating, FilterBar, Combobox, MultiSelect, DatePicker, TimePicker, FileUpload, Form, NumberInput, OtpInput, Segmented, ColorPicker, RichText, CodeEditor, Search, LocationPicker } from './input/index.js';
import { Table, Chart, VirtualList, Tree, Kanban, DataGrid, Sparkline, Gauge, Funnel, Heatmap, Sankey, Treemap, GanttChart, TreeTable, Calendar, Map as MapWidget } from './data/index.js';
import { If, Each } from './control/index.js';
import {
  Terminal, RippleFrame, AvatarGroup, ComparisonLayout,
  EntityDetail, FormLayout, WizardLayout, ChecklistLayout, ReportLayout, InvoiceLayout, OrderStatus,
  ExecDashboard, OpsDashboard, AnalyticsDashboard, PipelineDashboard, ProjectDashboard
} from './composite/index.js';
import { ConfirmDialog, Alert, DropdownMenu, Toast, Tooltip, Popover, HoverCard, CommandPalette, ContextMenu, NotificationCenter, ErrorState, Coachmark } from './overlay/index.js';
import {
  SourceCard, Citation, SourcesBar, DiscoverCard, FollowUp,
  CompanyHeader, Ticker, KvTable, Timeline, Callout, NewsCard,
  AnalystBar, RangeBar
} from './research/index.js';
import Workflow from './Workflow.svelte';
import { C4Diagram } from './c4/index.js';
import {
  PricingTable, SettingsList, CommentThread, AuditLog, ApiKey,
  BulkActionBar, SavedViews, PeoplePicker, PermissionMatrix, OrgChart, InvoiceLines
} from './vertical/index.js';
import { ModelViewer, Embed } from './media/index.js';
import { Reveal, Parallax } from './motion/index.js';
import { Navbar, Footer, Cta, Testimonial, FeatureGrid, Newsletter, LogoCloud } from './marketing/index.js';

/** Map of widget type name → Svelte component. Internal registry format. */
export type WidgetMap = Record<string, Component<any>>;

const defaultRegistry: WidgetMap = {
  container: Container,
  flex: Flex,
  grid: Grid,
  card: Card,
  tabs: Tabs,
  dashboard: Dashboard,
  'dashboard-slot': DashboardSlot,
  'glass-card': GlassCard,
  modal: Modal,
  dialog: Modal,
  accordion: Accordion,
  sheet: Sheet,
  drawer: Sheet,
  separator: Separator,
  divider: Separator,
  alert: Alert,
  banner: Alert,
  'dropdown-menu': DropdownMenu,
  dropdown: DropdownMenu,
  menu: DropdownMenu,
  'page-header': PageHeader,
  hero: Hero,
  section: Section,
  'empty-state': EmptyState,
  empty: EmptyState,
  'pros-cons': ProsCons,
  'comparison-table': ComparisonTable,
  comparison: ComparisonTable,
  steps: Steps,
  stepper: Steps,
  quote: Quote,
  pullquote: Quote,
  highlight: Highlight,
  'big-stat': Highlight,
  'definition-list': DefinitionList,
  dl: DefinitionList,
  glossary: DefinitionList,
  'article-meta': ArticleMeta,
  byline: ArticleMeta,
  sidebar: Sidebar,
  nav: Sidebar,
  'app-shell': AppShell,
  shell: AppShell,
  breadcrumb: Breadcrumb,
  breadcrumbs: Breadcrumb,
  split: Split,
  resizable: Split,
  'master-detail': MasterDetail,
  'list-detail': MasterDetail,
  text: Text,
  heading: Heading,
  image: Image,
  badge: Badge,
  progress: Progress,
  avatar: Avatar,
  metric: Metric,
  stat: Stat,
  'soul-status': SoulStatus,
  skeleton: Skeleton,
  markdown: Markdown,
  md: Markdown,
  'code-block': CodeBlock,
  code: Code,                         // CHANGED — inline; use 'code-block' for fenced
  button: Button,
  input: Input,
  select: Select,
  checkbox: Checkbox,
  switch: Switch,
  textarea: Textarea,
  slider: Slider,
  'radio-group': RadioGroup,
  radio: RadioGroup,
  rating: Rating,
  stars: Rating,
  'filter-bar': FilterBar,
  filters: FilterBar,
  combobox: Combobox,
  autocomplete: Combobox,
  'multi-select': MultiSelect,
  multiselect: MultiSelect,
  'tag-input': MultiSelect,
  'date-picker': DatePicker,
  datepicker: DatePicker,
  date: DatePicker,
  'time-picker': TimePicker,
  timepicker: TimePicker,
  time: TimePicker,
  'file-upload': FileUpload,
  fileupload: FileUpload,
  dropzone: FileUpload,
  form: Form,
  table: Table,
  'data-table': Table,
  datatable: Table,
  chart: Chart,
  'virtual-list': VirtualList,
  vlist: VirtualList,
  list: VirtualList,
  tree: Tree,
  treeview: Tree,
  kanban: Kanban,
  board: Kanban,
  'data-grid': DataGrid,
  datagrid: DataGrid,
  grid_table: DataGrid,
  sparkline: Sparkline,
  gauge: Gauge,
  funnel: Funnel,
  heatmap: Heatmap,
  sankey: Sankey,
  treemap: Treemap,
  'progress-ring': ProgressRing,
  ring: ProgressRing,
  'number-input': NumberInput,
  numberinput: NumberInput,
  number: NumberInput,
  'otp-input': OtpInput,
  otp: OtpInput,
  segmented: Segmented,
  'toggle-group': Segmented,
  collapsible: Collapsible,
  'color-picker': ColorPicker,
  color: ColorPicker,
  'rich-text': RichText,
  richtext: RichText,
  wysiwyg: RichText,
  'code-editor': CodeEditor,
  codeeditor: CodeEditor,
  editor: CodeEditor,
  gantt: GanttChart,
  'gantt-chart': GanttChart,
  search: Search,
  'tree-table': TreeTable,
  treetable: TreeTable,
  'nested-rows': TreeTable,
  calendar: Calendar,
  map: MapWidget,
  'geo-map': MapWidget,
  'tracking-map': MapWidget,
  'route-map': MapWidget,
  'location-picker': LocationPicker,
  'geo-picker': LocationPicker,
  'pick-location': LocationPicker,
  'context-menu': ContextMenu,
  contextmenu: ContextMenu,
  'notification-center': NotificationCenter,
  notifications: NotificationCenter,
  inbox: NotificationCenter,
  'error-state': ErrorState,
  error: ErrorState,
  mention: Mention,
  'link-preview': LinkPreview,
  linkpreview: LinkPreview,
  qr: Qr,
  qrcode: Qr,
  'qr-code': Qr,
  diff: Diff,
  coachmark: Coachmark,
  tour: Coachmark,
  // Enterprise verticals
  'pricing-table': PricingTable,
  pricing: PricingTable,
  'settings-list': SettingsList,
  settings: SettingsList,
  'comment-thread': CommentThread,
  comments: CommentThread,
  'audit-log': AuditLog,
  audit: AuditLog,
  'api-key': ApiKey,
  'secret-reveal': ApiKey,
  secret: ApiKey,
  'bulk-action-bar': BulkActionBar,
  bulk: BulkActionBar,
  'saved-views': SavedViews,
  views: SavedViews,
  'people-picker': PeoplePicker,
  people: PeoplePicker,
  'permission-matrix': PermissionMatrix,
  permissions: PermissionMatrix,
  'org-chart': OrgChart,
  orgchart: OrgChart,
  'invoice-lines': InvoiceLines,
  invoice: InvoiceLines,
  terminal: Terminal,
  'ripple-frame': RippleFrame,
  frame: RippleFrame,
  'nested-spec': RippleFrame,
  'comparison-layout': ComparisonLayout,
  'comparison-cards': ComparisonLayout,
  compare: ComparisonLayout,
  'entity-detail': EntityDetail,
  'record-detail': EntityDetail,
  'entity-page': EntityDetail,
  'form-layout': FormLayout,
  'wizard-layout': WizardLayout,
  wizard: WizardLayout,
  'checklist-layout': ChecklistLayout,
  checklist: ChecklistLayout,
  'report-layout': ReportLayout,
  report: ReportLayout,
  'invoice-layout': InvoiceLayout,
  'quote-layout': InvoiceLayout,
  receipt: InvoiceLayout,
  'order-status': OrderStatus,
  'shipment-tracker': OrderStatus,
  'order-tracking': OrderStatus,
  'exec-dashboard': ExecDashboard,
  'kpi-dashboard': ExecDashboard,
  'executive-dashboard': ExecDashboard,
  'ops-dashboard': OpsDashboard,
  'status-dashboard': OpsDashboard,
  'sre-dashboard': OpsDashboard,
  'analytics-dashboard': AnalyticsDashboard,
  'product-dashboard': AnalyticsDashboard,
  'pipeline-dashboard': PipelineDashboard,
  'sales-dashboard': PipelineDashboard,
  'funnel-dashboard': PipelineDashboard,
  'project-dashboard': ProjectDashboard,
  'team-dashboard': ProjectDashboard,
  if: If,
  each: Each,
  'source-card': SourceCard,
  citation: Citation,
  'sources-bar': SourcesBar,
  'discover-card': DiscoverCard,
  'follow-up': FollowUp,
  'company-header': CompanyHeader,
  ticker: Ticker,
  'kv-table': KvTable,
  timeline: Timeline,
  callout: Callout,
  'news-card': NewsCard,
  'analyst-bar': AnalystBar,
  'range-bar': RangeBar,
  workflow: Workflow,
  c4: C4Diagram,
  'confirm-dialog': ConfirmDialog,
  // Wave 1 additions
  tooltip: Tooltip,
  popover: Popover,
  'hover-card': HoverCard,
  hovercard: HoverCard,
  toast: Toast,
  'command-palette': CommandPalette,
  cmdk: CommandPalette,
  command: CommandPalette,
  loading: Loading,
  spinner: Loading,
  chip: Chip,
  tag: Chip,
  kbd: Kbd,
  'status-dot': StatusDot,
  status: StatusDot,
  trend: Trend,
  delta: Trend,
  icon: Icon,
  copy: Copy,
  'avatar-group': AvatarGroup,
  // Media — escape-hatch widgets (Increment 5)
  'model-viewer': ModelViewer,
  '3d': ModelViewer,
  model: ModelViewer,
  embed: Embed,
  iframe: Embed,
  // Motion — sugar widgets (RFC 12 animation primitive)
  reveal: Reveal,
  parallax: Parallax,
  // Marketing — landing-page widget pack (RFC 12)
  navbar: Navbar,
  footer: Footer,
  cta: Cta,
  'call-to-action': Cta,
  testimonial: Testimonial,
  'feature-grid': FeatureGrid,
  features: FeatureGrid,
  newsletter: Newsletter,
  'email-capture': Newsletter,
  'logo-cloud': LogoCloud,
  logos: LogoCloud,
  // Aliases
  label: Text,
};

let registry: WidgetMap = { ...defaultRegistry };

export function getWidget(type: string): Component<any> | undefined {
  return registry[type];
}

export function registerWidget(type: string, component: Component<any>): void {
  registry[type] = component;
}

export function unregisterWidget(type: string): void {
  delete registry[type];
}

export function hasWidget(type: string): boolean {
  return type in registry;
}

export function getWidgetTypes(): string[] {
  return Object.keys(registry);
}

export function resetRegistry(): void {
  registry = { ...defaultRegistry };
}

export {
  Container, Flex, Grid, Card, GlassCard, Tabs, Dashboard, DashboardSlot, Modal,
  Accordion, Sheet, Separator, Alert, PageHeader, Hero, Section, EmptyState, Sidebar, AppShell, Breadcrumb, Split, MasterDetail, Collapsible, DropdownMenu,
  ProsCons, ComparisonTable, Steps, Quote, Highlight, DefinitionList, ArticleMeta,
  Text, Heading, Image, Badge, Progress, Avatar, Metric, Stat, SoulStatus, Skeleton, Markdown, CodeBlock,
  Button, Input, Select, Checkbox, Switch, Textarea, Slider, RadioGroup, Rating, FilterBar, Combobox, MultiSelect, DatePicker, TimePicker, FileUpload, Form,
  NumberInput, OtpInput, Segmented, ColorPicker, RichText, CodeEditor, Search, LocationPicker,
  Table, Chart, VirtualList, Tree, Kanban, DataGrid, Sparkline, Gauge, Funnel, Heatmap, Sankey, Treemap, GanttChart, TreeTable, Calendar, MapWidget,
  ProgressRing, Mention, LinkPreview, Qr, Diff, Terminal, If, Each,
  SourceCard, Citation, SourcesBar, DiscoverCard, FollowUp,
  CompanyHeader, Ticker, KvTable, Timeline, Callout, NewsCard,
  AnalystBar, RangeBar,
  Workflow,
  C4Diagram,
  Toast, Tooltip, Popover, HoverCard, CommandPalette, ContextMenu, NotificationCenter, ErrorState, Coachmark,
  PricingTable, SettingsList, CommentThread, AuditLog, ApiKey,
  BulkActionBar, SavedViews, PeoplePicker, PermissionMatrix, OrgChart, InvoiceLines,
  Icon, Loading, Chip, Kbd, StatusDot, Trend, Copy, Code,
  AvatarGroup, ComparisonLayout,
  EntityDetail, FormLayout, WizardLayout, ChecklistLayout, ReportLayout, InvoiceLayout, OrderStatus,
  ExecDashboard, OpsDashboard, AnalyticsDashboard, PipelineDashboard, ProjectDashboard,
  ModelViewer, Embed,
  Reveal, Parallax,
  Navbar, Footer, Cta, Testimonial, FeatureGrid, Newsletter, LogoCloud
};
