// @file src/lib/widgets/index.ts
// @description GENERATED FILE — DO NOT EDIT BY HAND.
//   Produced by `bun run gen:widgets` from src/lib/widgets/registry.data.ts,
//   which is the source of truth for every widget type string and alias.
//   To add, rename, or alias a widget: edit registry.data.ts and regenerate.
//   `bun run lint:widgets` (and the vitest gate) fail if this file drifts.

import type { Component } from 'svelte';

import Workflow from './Workflow.svelte';
import {
  Container, Flex, Grid, Card, Tabs, Dashboard, DashboardSlot, GlassCard, Modal, Accordion, Sheet, Separator,
  PageHeader, Hero, Section, Sidebar, AppShell, Breadcrumb, Split, MasterDetail, Collapsible,
} from './layout/index.js';
import { DesignSystemEditor } from './design-system/index.js';
import {
  Alert, DropdownMenu, ContextMenu, NotificationCenter, ErrorState, Coachmark, ConfirmDialog, Tooltip,
  Popover, HoverCard, Toast, CommandPalette,
} from './overlay/index.js';
import {
  EmptyState, ProsCons, ComparisonTable, Steps, Quote, Highlight, DefinitionList, ArticleMeta, Text, Heading,
  Image, Badge, Progress, Avatar, Metric, Stat, SoulStatus, Skeleton, Markdown, CodeBlock, Code, ProgressRing,
  RichTextDisplay, Mention, LinkPreview, Qr, Diff, Loading, Chip, Kbd, StatusDot, Trend, Icon, Copy, LedClock,
  GlyphGrid, FillGrid, StreakBars,
} from './display/index.js';
import {
  Button, Input, Select, Checkbox, CheckboxGroup, Switch, Textarea, Slider, RadioGroup, Rating, FilterBar,
  Combobox, MultiSelect, DatePicker, TimePicker, FileUpload, Form, NumberInput, OtpInput, Segmented,
  ColorPicker, RichText, CodeEditor, Search, LocationPicker,
} from './input/index.js';
import {
  Table, Chart, VirtualList, Tree, Kanban, DataGrid, Sparkline, Gauge, Funnel, Heatmap, Sankey, Treemap,
  GanttChart, TreeTable, Calendar, Map as MapWidget, Seismograph,
} from './data/index.js';
import {
  PricingTable, SettingsList, CommentThread, AuditLog, ApiKey, BulkActionBar, SavedViews, PeoplePicker,
  PermissionMatrix, OrgChart, InvoiceLines,
} from './vertical/index.js';
import {
  Terminal, RippleFrame, ComparisonLayout, EntityDetail, FormLayout, WizardLayout, AskUserQuestions,
  ChecklistLayout, ReportLayout, InvoiceLayout, OrderStatus, ExecDashboard, OpsDashboard, AnalyticsDashboard,
  PipelineDashboard, ProjectDashboard, AvatarGroup,
} from './composite/index.js';
import { If, Each } from './control/index.js';
import {
  SourceCard, Citation, SourcesBar, DiscoverCard, FollowUp, CompanyHeader, Ticker, KvTable, Timeline, Callout,
  NewsCard, AnalystBar, RangeBar,
} from './research/index.js';
import { C4Diagram } from './c4/index.js';
import { ModelViewer, Embed, AudioPlayer, VideoPlayer } from './media/index.js';
import { Reveal, Parallax } from './motion/index.js';
import {
  Navbar, Footer, Cta, Testimonial, FeatureGrid, Newsletter, LogoCloud, Faq, MarketingHero,
} from './marketing/index.js';
import {
  Marquee, BorderBeam, Shimmer, AnimatedBeam, Aurora, Spotlight, BentoGrid, TextEffect,
} from './premium/index.js';
import { TodoList, DrawingCanvas, Timer, Flashcard } from './interactive/index.js';
import { StreamText, ToolCall, ReasoningTrace, ApprovalGate } from './ai/index.js';

/** Map of widget type name → Svelte component. Internal registry format. */
export type WidgetMap = Record<string, Component<any>>;

const defaultRegistry: WidgetMap = {
  container: Container,
  flex: Flex,
  grid: Grid,
  card: Card,
  tabs: Tabs,
  dashboard: Dashboard,
  'dashboard-slot': DashboardSlot,
  'design-system': DesignSystemEditor,
  'glass-card': GlassCard,
  modal: Modal,
  dialog: Modal,
  accordion: Accordion,
  sheet: Sheet,
  drawer: Sheet,
  separator: Separator,
  divider: Separator,
  alert: Alert,
  banner: Alert,
  'dropdown-menu': DropdownMenu,
  dropdown: DropdownMenu,
  menu: DropdownMenu,
  'page-header': PageHeader,
  hero: Hero,
  section: Section,
  'empty-state': EmptyState,
  empty: EmptyState,
  'pros-cons': ProsCons,
  'comparison-table': ComparisonTable,
  comparison: ComparisonTable,
  steps: Steps,
  stepper: Steps,
  quote: Quote,
  pullquote: Quote,
  highlight: Highlight,
  'big-stat': Highlight,
  'definition-list': DefinitionList,
  dl: DefinitionList,
  glossary: DefinitionList,
  'article-meta': ArticleMeta,
  byline: ArticleMeta,
  sidebar: Sidebar,
  nav: Sidebar,
  'app-shell': AppShell,
  shell: AppShell,
  breadcrumb: Breadcrumb,
  breadcrumbs: Breadcrumb,
  split: Split,
  resizable: Split,
  'master-detail': MasterDetail,
  'list-detail': MasterDetail,
  text: Text,
  label: Text,
  heading: Heading,
  image: Image,
  badge: Badge,
  progress: Progress,
  avatar: Avatar,
  metric: Metric,
  stat: Stat,
  'soul-status': SoulStatus,
  skeleton: Skeleton,
  markdown: Markdown,
  md: Markdown,
  'code-block': CodeBlock,
  // CHANGED — inline; use 'code-block' for fenced
  code: Code,
  button: Button,
  input: Input,
  select: Select,
  checkbox: Checkbox,
  'checkbox-group': CheckboxGroup,
  'checkbox-list': CheckboxGroup,
  switch: Switch,
  textarea: Textarea,
  slider: Slider,
  'radio-group': RadioGroup,
  radio: RadioGroup,
  rating: Rating,
  stars: Rating,
  'filter-bar': FilterBar,
  filters: FilterBar,
  combobox: Combobox,
  autocomplete: Combobox,
  'multi-select': MultiSelect,
  multiselect: MultiSelect,
  'tag-input': MultiSelect,
  'date-picker': DatePicker,
  datepicker: DatePicker,
  date: DatePicker,
  'time-picker': TimePicker,
  timepicker: TimePicker,
  time: TimePicker,
  'file-upload': FileUpload,
  fileupload: FileUpload,
  dropzone: FileUpload,
  form: Form,
  table: Table,
  'data-table': Table,
  datatable: Table,
  chart: Chart,
  'virtual-list': VirtualList,
  vlist: VirtualList,
  list: VirtualList,
  tree: Tree,
  treeview: Tree,
  kanban: Kanban,
  board: Kanban,
  'data-grid': DataGrid,
  datagrid: DataGrid,
  grid_table: DataGrid,
  sparkline: Sparkline,
  gauge: Gauge,
  funnel: Funnel,
  heatmap: Heatmap,
  sankey: Sankey,
  treemap: Treemap,
  'progress-ring': ProgressRing,
  ring: ProgressRing,
  'number-input': NumberInput,
  numberinput: NumberInput,
  number: NumberInput,
  'otp-input': OtpInput,
  otp: OtpInput,
  segmented: Segmented,
  'toggle-group': Segmented,
  collapsible: Collapsible,
  'color-picker': ColorPicker,
  color: ColorPicker,
  'rich-text': RichText,
  wysiwyg: RichText,
  // CONTRACT CHANGE (editor chrome, 2026-06-30): `richtext` (no hyphen) now maps
  // to the DISPLAY widget RichTextDisplay (renders trusted rich HTML), not the
  // WYSIWYG input. The input editor is still reachable as `rich-text` / `wysiwyg`.
  // Captain accepted this so the visual editor's inline TipTap path authors a
  // `richtext` node's `html` prop and the same node renders the committed result.
  richtext: RichTextDisplay,
  'code-editor': CodeEditor,
  codeeditor: CodeEditor,
  editor: CodeEditor,
  gantt: GanttChart,
  'gantt-chart': GanttChart,
  search: Search,
  'tree-table': TreeTable,
  treetable: TreeTable,
  'nested-rows': TreeTable,
  calendar: Calendar,
  map: MapWidget,
  'geo-map': MapWidget,
  'tracking-map': MapWidget,
  'route-map': MapWidget,
  'location-picker': LocationPicker,
  'geo-picker': LocationPicker,
  'pick-location': LocationPicker,
  'context-menu': ContextMenu,
  contextmenu: ContextMenu,
  'notification-center': NotificationCenter,
  notifications: NotificationCenter,
  inbox: NotificationCenter,
  'error-state': ErrorState,
  error: ErrorState,
  mention: Mention,
  'link-preview': LinkPreview,
  linkpreview: LinkPreview,
  qr: Qr,
  qrcode: Qr,
  'qr-code': Qr,
  diff: Diff,
  coachmark: Coachmark,
  tour: Coachmark,
  // Enterprise verticals
  'pricing-table': PricingTable,
  pricing: PricingTable,
  'settings-list': SettingsList,
  settings: SettingsList,
  'comment-thread': CommentThread,
  comments: CommentThread,
  'audit-log': AuditLog,
  audit: AuditLog,
  'api-key': ApiKey,
  'secret-reveal': ApiKey,
  secret: ApiKey,
  'bulk-action-bar': BulkActionBar,
  bulk: BulkActionBar,
  'saved-views': SavedViews,
  views: SavedViews,
  'people-picker': PeoplePicker,
  people: PeoplePicker,
  'permission-matrix': PermissionMatrix,
  permissions: PermissionMatrix,
  'org-chart': OrgChart,
  orgchart: OrgChart,
  'invoice-lines': InvoiceLines,
  invoice: InvoiceLines,
  terminal: Terminal,
  'ripple-frame': RippleFrame,
  frame: RippleFrame,
  'nested-spec': RippleFrame,
  'comparison-layout': ComparisonLayout,
  'comparison-cards': ComparisonLayout,
  compare: ComparisonLayout,
  'entity-detail': EntityDetail,
  'record-detail': EntityDetail,
  'entity-page': EntityDetail,
  'form-layout': FormLayout,
  'wizard-layout': WizardLayout,
  wizard: WizardLayout,
  'ask-user-questions': AskUserQuestions,
  ask_user_questions: AskUserQuestions,
  'user-questions': AskUserQuestions,
  questionnaire: AskUserQuestions,
  'checklist-layout': ChecklistLayout,
  checklist: ChecklistLayout,
  'report-layout': ReportLayout,
  report: ReportLayout,
  'invoice-layout': InvoiceLayout,
  'quote-layout': InvoiceLayout,
  receipt: InvoiceLayout,
  'order-status': OrderStatus,
  'shipment-tracker': OrderStatus,
  'order-tracking': OrderStatus,
  'exec-dashboard': ExecDashboard,
  'kpi-dashboard': ExecDashboard,
  'executive-dashboard': ExecDashboard,
  'ops-dashboard': OpsDashboard,
  'status-dashboard': OpsDashboard,
  'sre-dashboard': OpsDashboard,
  'analytics-dashboard': AnalyticsDashboard,
  'product-dashboard': AnalyticsDashboard,
  'pipeline-dashboard': PipelineDashboard,
  'sales-dashboard': PipelineDashboard,
  'funnel-dashboard': PipelineDashboard,
  'project-dashboard': ProjectDashboard,
  'team-dashboard': ProjectDashboard,
  if: If,
  each: Each,
  'source-card': SourceCard,
  citation: Citation,
  'sources-bar': SourcesBar,
  'discover-card': DiscoverCard,
  'follow-up': FollowUp,
  'company-header': CompanyHeader,
  ticker: Ticker,
  'kv-table': KvTable,
  timeline: Timeline,
  callout: Callout,
  'news-card': NewsCard,
  'analyst-bar': AnalystBar,
  'range-bar': RangeBar,
  workflow: Workflow,
  c4: C4Diagram,
  'confirm-dialog': ConfirmDialog,
  // Wave 1 additions
  tooltip: Tooltip,
  popover: Popover,
  'hover-card': HoverCard,
  hovercard: HoverCard,
  toast: Toast,
  'command-palette': CommandPalette,
  cmdk: CommandPalette,
  command: CommandPalette,
  loading: Loading,
  spinner: Loading,
  chip: Chip,
  tag: Chip,
  kbd: Kbd,
  'status-dot': StatusDot,
  status: StatusDot,
  trend: Trend,
  delta: Trend,
  icon: Icon,
  copy: Copy,
  'avatar-group': AvatarGroup,
  // Media — escape-hatch widgets (Increment 5)
  'model-viewer': ModelViewer,
  '3d': ModelViewer,
  model: ModelViewer,
  embed: Embed,
  iframe: Embed,
  // Motion — sugar widgets (RFC 12 animation primitive)
  reveal: Reveal,
  parallax: Parallax,
  // Marketing — landing-page widget pack (RFC 12)
  navbar: Navbar,
  footer: Footer,
  cta: Cta,
  'call-to-action': Cta,
  testimonial: Testimonial,
  'feature-grid': FeatureGrid,
  features: FeatureGrid,
  newsletter: Newsletter,
  'email-capture': Newsletter,
  'logo-cloud': LogoCloud,
  logos: LogoCloud,
  faq: Faq,
  faqs: Faq,
  'marketing-hero': MarketingHero,
  // Premium — MIT-ported animation pack (RFC 12)
  marquee: Marquee,
  'border-beam': BorderBeam,
  shimmer: Shimmer,
  'animated-beam': AnimatedBeam,
  aurora: Aurora,
  'aurora-background': Aurora,
  spotlight: Spotlight,
  'bento-grid': BentoGrid,
  bento: BentoGrid,
  'text-effect': TextEffect,
  'animated-text': TextEffect,
  // Media — native players (composite consumer widgets, 2026-05-31)
  audio: AudioPlayer,
  'audio-player': AudioPlayer,
  video: VideoPlayer,
  'video-player': VideoPlayer,
  // Interactive — self-contained consumer widgets (2026-05-31)
  'todo-list': TodoList,
  todo: TodoList,
  todos: TodoList,
  'drawing-canvas': DrawingCanvas,
  drawing: DrawingCanvas,
  canvas: DrawingCanvas,
  sketchpad: DrawingCanvas,
  timer: Timer,
  countdown: Timer,
  pomodoro: Timer,
  flashcard: Flashcard,
  'flip-card': Flashcard,
  // Console telemetry pack (feat/console-telemetry-widgets, 2026-06-13)
  'led-clock': LedClock,
  ledclock: LedClock,
  'dot-matrix': LedClock,
  seismograph: Seismograph,
  trace: Seismograph,
  oscilloscope: Seismograph,
  'glyph-grid': GlyphGrid,
  glyphgrid: GlyphGrid,
  glyph: GlyphGrid,
  'fill-grid': FillGrid,
  fillgrid: FillGrid,
  'heap-meter': FillGrid,
  'streak-bars': StreakBars,
  streakbars: StreakBars,
  streak: StreakBars,
  // AI-native display tier (feat/ai-native-widgets, 2026-06-24)
  'stream-text': StreamText,
  streamtext: StreamText,
  'streaming-text': StreamText,
  'tool-call': ToolCall,
  toolcall: ToolCall,
  'tool-invocation': ToolCall,
  'reasoning-trace': ReasoningTrace,
  reasoning: ReasoningTrace,
  'thinking-trace': ReasoningTrace,
  'approval-gate': ApprovalGate,
  approval: ApprovalGate,
  'approve-card': ApprovalGate,
  'human-gate': ApprovalGate,
};

let registry: WidgetMap = { ...defaultRegistry };

export function getWidget(type: string): Component<any> | undefined {
  return registry[type];
}

export function registerWidget(type: string, component: Component<any>): void {
  registry[type] = component;
}

export function unregisterWidget(type: string): void {
  delete registry[type];
}

export function hasWidget(type: string): boolean {
  return type in registry;
}

export function getWidgetTypes(): string[] {
  return Object.keys(registry);
}

export function resetRegistry(): void {
  registry = { ...defaultRegistry };
}

export {
  Container, Flex, Grid, Card, Tabs, Dashboard, DashboardSlot, GlassCard, Modal, Accordion, Sheet, Separator,
  Alert, DropdownMenu, PageHeader, Hero, Section, EmptyState, ProsCons, ComparisonTable, Steps, Quote,
  Highlight, DefinitionList, ArticleMeta, Sidebar, AppShell, Breadcrumb, Split, MasterDetail, Text, Heading,
  Image, Badge, Progress, Avatar, Metric, Stat, SoulStatus, Skeleton, Markdown, CodeBlock, Code, Button,
  Input, Select, Checkbox, CheckboxGroup, Switch, Textarea, Slider, RadioGroup, Rating, FilterBar, Combobox,
  MultiSelect, DatePicker, TimePicker, FileUpload, Form, Table, Chart, VirtualList, Tree, Kanban, DataGrid,
  Sparkline, Gauge, Funnel, Heatmap, Sankey, Treemap, ProgressRing, NumberInput, OtpInput, Segmented,
  Collapsible, ColorPicker, RichText, RichTextDisplay, CodeEditor, GanttChart, Search, TreeTable, Calendar,
  MapWidget, LocationPicker, ContextMenu, NotificationCenter, ErrorState, Mention, LinkPreview, Qr, Diff,
  Coachmark, PricingTable, SettingsList, CommentThread, AuditLog, ApiKey, BulkActionBar, SavedViews,
  PeoplePicker, PermissionMatrix, OrgChart, InvoiceLines, Terminal, ComparisonLayout, EntityDetail,
  FormLayout, WizardLayout, AskUserQuestions, ChecklistLayout, ReportLayout, InvoiceLayout, OrderStatus,
  ExecDashboard, OpsDashboard, AnalyticsDashboard, PipelineDashboard, ProjectDashboard, If, Each, SourceCard,
  Citation, SourcesBar, DiscoverCard, FollowUp, CompanyHeader, Ticker, KvTable, Timeline, Callout, NewsCard,
  AnalystBar, RangeBar, Workflow, C4Diagram, Tooltip, Popover, HoverCard, Toast, CommandPalette, Loading,
  Chip, Kbd, StatusDot, Trend, Icon, Copy, AvatarGroup, ModelViewer, Embed, Reveal, Parallax, Navbar, Footer,
  Cta, Testimonial, FeatureGrid, Newsletter, LogoCloud, Faq, MarketingHero, Marquee, BorderBeam, Shimmer,
  AnimatedBeam, Aurora, Spotlight, BentoGrid, TextEffect, AudioPlayer, VideoPlayer, TodoList, DrawingCanvas,
  Timer, Flashcard, LedClock, Seismograph, GlyphGrid, FillGrid, StreakBars, StreamText, ToolCall,
  ReasoningTrace, ApprovalGate,
};
