// @file src/lib/widgets/registry.data.ts
// @description SOURCE OF TRUTH for the widget registry. Every widget the
//   renderer can mount is declared here once — component name, source module,
//   its canonical type string, every alias it answers to, and whether it is
//   part of the package's public export surface. `src/lib/widgets/index.ts` is
//   GENERATED from this file by `bun run gen:widgets`; never hand-edit it.
//   Adding a widget = add its barrel export + one entry below, nothing else.
// @created 2026-08-24 — replaces the hand-maintained import wall.

/** One widget: how to import it, what type strings resolve to it. */
export interface WidgetRegistryEntry {
  /** Local identifier used in the generated file (also the exported name). */
  component: string;
  /** Module specifier to import from, relative to widgets/index.ts. */
  from: string;
  /** Set when the module exports it under a different name (`Map as MapWidget`). */
  imported?: string;
  /** Set for a default import from a .svelte file rather than a barrel. */
  default?: boolean;
  /** Type strings that resolve to this widget. First is canonical; rest aliases. */
  types: readonly string[];
  /** false = registered but deliberately NOT re-exported from the package. */
  exported?: boolean;
  /** Verbatim comment lines emitted above the entry in the generated file. */
  note?: readonly string[];
}

export const WIDGET_REGISTRY: readonly WidgetRegistryEntry[] = [
  { component: 'Container', from: './layout/index.js', types: ['container'] },
  { component: 'Flex', from: './layout/index.js', types: ['flex'] },
  { component: 'Grid', from: './layout/index.js', types: ['grid'] },
  { component: 'Card', from: './layout/index.js', types: ['card'] },
  { component: 'Tabs', from: './layout/index.js', types: ['tabs'] },
  { component: 'Dashboard', from: './layout/index.js', types: ['dashboard'] },
  { component: 'DashboardSlot', from: './layout/index.js', types: ['dashboard-slot'] },
  { component: 'DesignSystemEditor', from: './design-system/index.js', types: ['design-system'], exported: false },
  { component: 'GlassCard', from: './layout/index.js', types: ['glass-card'] },
  { component: 'Modal', from: './layout/index.js', types: ['modal', 'dialog'] },
  { component: 'Accordion', from: './layout/index.js', types: ['accordion'] },
  { component: 'Sheet', from: './layout/index.js', types: ['sheet', 'drawer'] },
  { component: 'Separator', from: './layout/index.js', types: ['separator', 'divider'] },
  { component: 'Alert', from: './overlay/index.js', types: ['alert', 'banner'] },
  { component: 'DropdownMenu', from: './overlay/index.js', types: ['dropdown-menu', 'dropdown', 'menu'] },
  { component: 'PageHeader', from: './layout/index.js', types: ['page-header'] },
  { component: 'Hero', from: './layout/index.js', types: ['hero'] },
  { component: 'Section', from: './layout/index.js', types: ['section'] },
  { component: 'EmptyState', from: './display/index.js', types: ['empty-state', 'empty'] },
  { component: 'ProsCons', from: './display/index.js', types: ['pros-cons'] },
  { component: 'ComparisonTable', from: './display/index.js', types: ['comparison-table', 'comparison'] },
  { component: 'Steps', from: './display/index.js', types: ['steps', 'stepper'] },
  { component: 'Quote', from: './display/index.js', types: ['quote', 'pullquote'] },
  { component: 'Highlight', from: './display/index.js', types: ['highlight', 'big-stat'] },
  { component: 'DefinitionList', from: './display/index.js', types: ['definition-list', 'dl', 'glossary'] },
  { component: 'ArticleMeta', from: './display/index.js', types: ['article-meta', 'byline'] },
  { component: 'Sidebar', from: './layout/index.js', types: ['sidebar', 'nav'] },
  { component: 'AppShell', from: './layout/index.js', types: ['app-shell', 'shell'] },
  { component: 'Breadcrumb', from: './layout/index.js', types: ['breadcrumb', 'breadcrumbs'] },
  { component: 'Split', from: './layout/index.js', types: ['split', 'resizable'] },
  { component: 'MasterDetail', from: './layout/index.js', types: ['master-detail', 'list-detail'] },
  { component: 'Text', from: './display/index.js', types: ['text', 'label'] },
  { component: 'Heading', from: './display/index.js', types: ['heading'] },
  { component: 'Image', from: './display/index.js', types: ['image'] },
  { component: 'Badge', from: './display/index.js', types: ['badge'] },
  { component: 'Progress', from: './display/index.js', types: ['progress'] },
  { component: 'Avatar', from: './display/index.js', types: ['avatar'] },
  { component: 'Metric', from: './display/index.js', types: ['metric'] },
  { component: 'Stat', from: './display/index.js', types: ['stat'] },
  { component: 'SoulStatus', from: './display/index.js', types: ['soul-status'] },
  { component: 'Skeleton', from: './display/index.js', types: ['skeleton'] },
  { component: 'Markdown', from: './display/index.js', types: ['markdown', 'md'] },
  { component: 'CodeBlock', from: './display/index.js', types: ['code-block'] },
  {
    component: 'Code',
    from: './display/index.js',
    types: ['code'],
    note: ['CHANGED — inline; use \'code-block\' for fenced'],
  },
  { component: 'Button', from: './input/index.js', types: ['button'] },
  { component: 'Input', from: './input/index.js', types: ['input'] },
  { component: 'Select', from: './input/index.js', types: ['select'] },
  { component: 'Checkbox', from: './input/index.js', types: ['checkbox'] },
  { component: 'CheckboxGroup', from: './input/index.js', types: ['checkbox-group', 'checkbox-list'] },
  { component: 'Switch', from: './input/index.js', types: ['switch'] },
  { component: 'Textarea', from: './input/index.js', types: ['textarea'] },
  { component: 'Slider', from: './input/index.js', types: ['slider'] },
  { component: 'RadioGroup', from: './input/index.js', types: ['radio-group', 'radio'] },
  { component: 'Rating', from: './input/index.js', types: ['rating', 'stars'] },
  { component: 'FilterBar', from: './input/index.js', types: ['filter-bar', 'filters'] },
  { component: 'Combobox', from: './input/index.js', types: ['combobox', 'autocomplete'] },
  { component: 'MultiSelect', from: './input/index.js', types: ['multi-select', 'multiselect', 'tag-input'] },
  { component: 'DatePicker', from: './input/index.js', types: ['date-picker', 'datepicker', 'date'] },
  { component: 'TimePicker', from: './input/index.js', types: ['time-picker', 'timepicker', 'time'] },
  { component: 'FileUpload', from: './input/index.js', types: ['file-upload', 'fileupload', 'dropzone'] },
  { component: 'Form', from: './input/index.js', types: ['form'] },
  { component: 'Table', from: './data/index.js', types: ['table', 'data-table', 'datatable'] },
  { component: 'Chart', from: './data/index.js', types: ['chart'] },
  { component: 'VirtualList', from: './data/index.js', types: ['virtual-list', 'vlist', 'list'] },
  { component: 'Tree', from: './data/index.js', types: ['tree', 'treeview'] },
  { component: 'Kanban', from: './data/index.js', types: ['kanban', 'board'] },
  { component: 'DataGrid', from: './data/index.js', types: ['data-grid', 'datagrid', 'grid_table'] },
  { component: 'Sparkline', from: './data/index.js', types: ['sparkline'] },
  { component: 'Gauge', from: './data/index.js', types: ['gauge'] },
  { component: 'Funnel', from: './data/index.js', types: ['funnel'] },
  { component: 'Heatmap', from: './data/index.js', types: ['heatmap'] },
  { component: 'Sankey', from: './data/index.js', types: ['sankey'] },
  { component: 'Treemap', from: './data/index.js', types: ['treemap'] },
  { component: 'ProgressRing', from: './display/index.js', types: ['progress-ring', 'ring'] },
  { component: 'NumberInput', from: './input/index.js', types: ['number-input', 'numberinput', 'number'] },
  { component: 'OtpInput', from: './input/index.js', types: ['otp-input', 'otp'] },
  { component: 'Segmented', from: './input/index.js', types: ['segmented', 'toggle-group'] },
  { component: 'Collapsible', from: './layout/index.js', types: ['collapsible'] },
  { component: 'ColorPicker', from: './input/index.js', types: ['color-picker', 'color'] },
  { component: 'RichText', from: './input/index.js', types: ['rich-text', 'wysiwyg'] },
  {
    component: 'RichTextDisplay',
    from: './display/index.js',
    types: ['richtext'],
    note: [
      'CONTRACT CHANGE (editor chrome, 2026-06-30): `richtext` (no hyphen) now maps',
      'to the DISPLAY widget RichTextDisplay (renders trusted rich HTML), not the',
      'WYSIWYG input. The input editor is still reachable as `rich-text` / `wysiwyg`.',
      'Captain accepted this so the visual editor\'s inline TipTap path authors a',
      '`richtext` node\'s `html` prop and the same node renders the committed result.',
    ],
  },
  { component: 'CodeEditor', from: './input/index.js', types: ['code-editor', 'codeeditor', 'editor'] },
  { component: 'GanttChart', from: './data/index.js', types: ['gantt', 'gantt-chart'] },
  { component: 'Search', from: './input/index.js', types: ['search'] },
  { component: 'TreeTable', from: './data/index.js', types: ['tree-table', 'treetable', 'nested-rows'] },
  { component: 'Calendar', from: './data/index.js', types: ['calendar'] },
  {
    component: 'MapWidget',
    from: './data/index.js',
    imported: 'Map',
    types: ['map', 'geo-map', 'tracking-map', 'route-map'],
  },
  {
    component: 'LocationPicker',
    from: './input/index.js',
    types: ['location-picker', 'geo-picker', 'pick-location'],
  },
  { component: 'ContextMenu', from: './overlay/index.js', types: ['context-menu', 'contextmenu'] },
  {
    component: 'NotificationCenter',
    from: './overlay/index.js',
    types: ['notification-center', 'notifications', 'inbox'],
  },
  { component: 'ErrorState', from: './overlay/index.js', types: ['error-state', 'error'] },
  { component: 'Mention', from: './display/index.js', types: ['mention'] },
  { component: 'LinkPreview', from: './display/index.js', types: ['link-preview', 'linkpreview'] },
  { component: 'Qr', from: './display/index.js', types: ['qr', 'qrcode', 'qr-code'] },
  { component: 'Diff', from: './display/index.js', types: ['diff'] },
  { component: 'Coachmark', from: './overlay/index.js', types: ['coachmark', 'tour'] },
  {
    component: 'PricingTable',
    from: './vertical/index.js',
    types: ['pricing-table', 'pricing'],
    note: ['Enterprise verticals'],
  },
  { component: 'SettingsList', from: './vertical/index.js', types: ['settings-list', 'settings'] },
  { component: 'CommentThread', from: './vertical/index.js', types: ['comment-thread', 'comments'] },
  { component: 'AuditLog', from: './vertical/index.js', types: ['audit-log', 'audit'] },
  { component: 'ApiKey', from: './vertical/index.js', types: ['api-key', 'secret-reveal', 'secret'] },
  { component: 'BulkActionBar', from: './vertical/index.js', types: ['bulk-action-bar', 'bulk'] },
  { component: 'SavedViews', from: './vertical/index.js', types: ['saved-views', 'views'] },
  { component: 'PeoplePicker', from: './vertical/index.js', types: ['people-picker', 'people'] },
  { component: 'PermissionMatrix', from: './vertical/index.js', types: ['permission-matrix', 'permissions'] },
  { component: 'OrgChart', from: './vertical/index.js', types: ['org-chart', 'orgchart'] },
  { component: 'InvoiceLines', from: './vertical/index.js', types: ['invoice-lines', 'invoice'] },
  { component: 'Terminal', from: './composite/index.js', types: ['terminal'] },
  {
    component: 'RippleFrame',
    from: './composite/index.js',
    types: ['ripple-frame', 'frame', 'nested-spec'],
    exported: false,
  },
  {
    component: 'ComparisonLayout',
    from: './composite/index.js',
    types: ['comparison-layout', 'comparison-cards', 'compare'],
  },
  {
    component: 'EntityDetail',
    from: './composite/index.js',
    types: ['entity-detail', 'record-detail', 'entity-page'],
  },
  { component: 'FormLayout', from: './composite/index.js', types: ['form-layout'] },
  { component: 'WizardLayout', from: './composite/index.js', types: ['wizard-layout', 'wizard'] },
  {
    component: 'AskUserQuestions',
    from: './composite/index.js',
    types: ['ask-user-questions', 'ask_user_questions', 'user-questions', 'questionnaire'],
  },
  { component: 'ChecklistLayout', from: './composite/index.js', types: ['checklist-layout', 'checklist'] },
  { component: 'ReportLayout', from: './composite/index.js', types: ['report-layout', 'report'] },
  { component: 'InvoiceLayout', from: './composite/index.js', types: ['invoice-layout', 'quote-layout', 'receipt'] },
  {
    component: 'OrderStatus',
    from: './composite/index.js',
    types: ['order-status', 'shipment-tracker', 'order-tracking'],
  },
  {
    component: 'ExecDashboard',
    from: './composite/index.js',
    types: ['exec-dashboard', 'kpi-dashboard', 'executive-dashboard'],
  },
  {
    component: 'OpsDashboard',
    from: './composite/index.js',
    types: ['ops-dashboard', 'status-dashboard', 'sre-dashboard'],
  },
  {
    component: 'AnalyticsDashboard',
    from: './composite/index.js',
    types: ['analytics-dashboard', 'product-dashboard'],
  },
  {
    component: 'PipelineDashboard',
    from: './composite/index.js',
    types: ['pipeline-dashboard', 'sales-dashboard', 'funnel-dashboard'],
  },
  { component: 'ProjectDashboard', from: './composite/index.js', types: ['project-dashboard', 'team-dashboard'] },
  { component: 'If', from: './control/index.js', types: ['if'] },
  { component: 'Each', from: './control/index.js', types: ['each'] },
  { component: 'SourceCard', from: './research/index.js', types: ['source-card'] },
  { component: 'Citation', from: './research/index.js', types: ['citation'] },
  { component: 'SourcesBar', from: './research/index.js', types: ['sources-bar'] },
  { component: 'DiscoverCard', from: './research/index.js', types: ['discover-card'] },
  { component: 'FollowUp', from: './research/index.js', types: ['follow-up'] },
  { component: 'CompanyHeader', from: './research/index.js', types: ['company-header'] },
  { component: 'Ticker', from: './research/index.js', types: ['ticker'] },
  { component: 'KvTable', from: './research/index.js', types: ['kv-table'] },
  { component: 'Timeline', from: './research/index.js', types: ['timeline'] },
  { component: 'Callout', from: './research/index.js', types: ['callout'] },
  { component: 'NewsCard', from: './research/index.js', types: ['news-card'] },
  { component: 'AnalystBar', from: './research/index.js', types: ['analyst-bar'] },
  { component: 'RangeBar', from: './research/index.js', types: ['range-bar'] },
  { component: 'Workflow', from: './Workflow.svelte', default: true, types: ['workflow'] },
  { component: 'C4Diagram', from: './c4/index.js', types: ['c4'] },
  { component: 'ConfirmDialog', from: './overlay/index.js', types: ['confirm-dialog'], exported: false },
  { component: 'Tooltip', from: './overlay/index.js', types: ['tooltip'], note: ['Wave 1 additions'] },
  { component: 'Popover', from: './overlay/index.js', types: ['popover'] },
  { component: 'HoverCard', from: './overlay/index.js', types: ['hover-card', 'hovercard'] },
  { component: 'Toast', from: './overlay/index.js', types: ['toast'] },
  { component: 'CommandPalette', from: './overlay/index.js', types: ['command-palette', 'cmdk', 'command'] },
  { component: 'Loading', from: './display/index.js', types: ['loading', 'spinner'] },
  { component: 'Chip', from: './display/index.js', types: ['chip', 'tag'] },
  { component: 'Kbd', from: './display/index.js', types: ['kbd'] },
  { component: 'StatusDot', from: './display/index.js', types: ['status-dot', 'status'] },
  { component: 'Trend', from: './display/index.js', types: ['trend', 'delta'] },
  { component: 'Icon', from: './display/index.js', types: ['icon'] },
  { component: 'Copy', from: './display/index.js', types: ['copy'] },
  { component: 'AvatarGroup', from: './composite/index.js', types: ['avatar-group'] },
  {
    component: 'ModelViewer',
    from: './media/index.js',
    types: ['model-viewer', '3d', 'model'],
    note: ['Media — escape-hatch widgets (Increment 5)'],
  },
  { component: 'Embed', from: './media/index.js', types: ['embed', 'iframe'] },
  {
    component: 'Reveal',
    from: './motion/index.js',
    types: ['reveal'],
    note: ['Motion — sugar widgets (RFC 12 animation primitive)'],
  },
  { component: 'Parallax', from: './motion/index.js', types: ['parallax'] },
  {
    component: 'Navbar',
    from: './marketing/index.js',
    types: ['navbar'],
    note: ['Marketing — landing-page widget pack (RFC 12)'],
  },
  { component: 'Footer', from: './marketing/index.js', types: ['footer'] },
  { component: 'Cta', from: './marketing/index.js', types: ['cta', 'call-to-action'] },
  { component: 'Testimonial', from: './marketing/index.js', types: ['testimonial'] },
  { component: 'FeatureGrid', from: './marketing/index.js', types: ['feature-grid', 'features'] },
  { component: 'Newsletter', from: './marketing/index.js', types: ['newsletter', 'email-capture'] },
  { component: 'LogoCloud', from: './marketing/index.js', types: ['logo-cloud', 'logos'] },
  { component: 'Faq', from: './marketing/index.js', types: ['faq', 'faqs'] },
  { component: 'MarketingHero', from: './marketing/index.js', types: ['marketing-hero'] },
  {
    component: 'Marquee',
    from: './premium/index.js',
    types: ['marquee'],
    note: ['Premium — MIT-ported animation pack (RFC 12)'],
  },
  { component: 'BorderBeam', from: './premium/index.js', types: ['border-beam'] },
  { component: 'Shimmer', from: './premium/index.js', types: ['shimmer'] },
  { component: 'AnimatedBeam', from: './premium/index.js', types: ['animated-beam'] },
  { component: 'Aurora', from: './premium/index.js', types: ['aurora', 'aurora-background'] },
  { component: 'Spotlight', from: './premium/index.js', types: ['spotlight'] },
  { component: 'BentoGrid', from: './premium/index.js', types: ['bento-grid', 'bento'] },
  { component: 'TextEffect', from: './premium/index.js', types: ['text-effect', 'animated-text'] },
  {
    component: 'AudioPlayer',
    from: './media/index.js',
    types: ['audio', 'audio-player'],
    note: ['Media — native players (composite consumer widgets, 2026-05-31)'],
  },
  { component: 'VideoPlayer', from: './media/index.js', types: ['video', 'video-player'] },
  {
    component: 'TodoList',
    from: './interactive/index.js',
    types: ['todo-list', 'todo', 'todos'],
    note: ['Interactive — self-contained consumer widgets (2026-05-31)'],
  },
  {
    component: 'DrawingCanvas',
    from: './interactive/index.js',
    types: ['drawing-canvas', 'drawing', 'canvas', 'sketchpad'],
  },
  { component: 'Timer', from: './interactive/index.js', types: ['timer', 'countdown', 'pomodoro'] },
  { component: 'Flashcard', from: './interactive/index.js', types: ['flashcard', 'flip-card'] },
  {
    component: 'LedClock',
    from: './display/index.js',
    types: ['led-clock', 'ledclock', 'dot-matrix'],
    note: ['Console telemetry pack (feat/console-telemetry-widgets, 2026-06-13)'],
  },
  { component: 'Seismograph', from: './data/index.js', types: ['seismograph', 'trace', 'oscilloscope'] },
  { component: 'GlyphGrid', from: './display/index.js', types: ['glyph-grid', 'glyphgrid', 'glyph'] },
  { component: 'FillGrid', from: './display/index.js', types: ['fill-grid', 'fillgrid', 'heap-meter'] },
  { component: 'StreakBars', from: './display/index.js', types: ['streak-bars', 'streakbars', 'streak'] },
  {
    component: 'StreamText',
    from: './ai/index.js',
    types: ['stream-text', 'streamtext', 'streaming-text'],
    note: ['AI-native display tier (feat/ai-native-widgets, 2026-06-24)'],
  },
  { component: 'ToolCall', from: './ai/index.js', types: ['tool-call', 'toolcall', 'tool-invocation'] },
  { component: 'ReasoningTrace', from: './ai/index.js', types: ['reasoning-trace', 'reasoning', 'thinking-trace'] },
  {
    component: 'ApprovalGate',
    from: './ai/index.js',
    types: ['approval-gate', 'approval', 'approve-card', 'human-gate'],
  },
];
