import type { WidgetManifestEntry } from '../index.js';

export const comparisonLayoutEntry: WidgetManifestEntry = {
  type: 'comparison-layout',
  category: 'composite',
  description:
    'Side-by-side comparison of 2–6 items with hero cards, section-tab feature grid, and Card/Table view toggle. Per-item `actions` and `learn_more` accept ripple event handlers.',
  props: {
    title: { type: 'string', required: false, description: 'Header title.' },
    description: { type: 'string', required: false, description: 'Subheader description.' },
    items: {
      type: 'Array<{ id: string; title?: string; name?: string; subtitle?: string; chip?: string; image?: string; price?: string | number; actions?: EventAction | EventAction[]; learn_more?: EventAction | EventAction[]; [featureKey: string]: unknown }>',
      required: true,
      description: 'Items being compared. Extra keys become feature values; `actions` and `learn_more` carry per-item event handlers.',
    },
    features: {
      type: 'Array<{ key: string; label: string; section?: string; type?: "text" | "boolean" | "rating" | "image" | "color"; icon?: string; highlight?: boolean }>',
      required: false,
      description: 'Explicit feature definitions. If omitted, features are inferred from item keys (text/boolean only) and grouped under a single "Features" section. Use `section` to group features into tabs, `highlight: true` to surface a feature as a spec pill on the card, and `type` to control rendering.',
    },
    primaryLabel: { type: 'string', required: false, description: 'Primary CTA label. Default "Select".' },
    secondaryLabel: { type: 'string', required: false, description: 'Secondary "Learn more" label. Default "Learn more".' },
    showPrimary: { type: 'boolean', required: false, description: 'Render the primary CTA. Default true.' },
    showSecondary: { type: 'boolean', required: false, description: 'Render the "Learn more" button. Default true.' },
    defaultView: { type: '"card" | "table"', required: false, description: 'Initial view mode for the detailed feature grid on mobile. Default "card". Desktop always shows the table.' },
    showDiffToggle: { type: 'boolean', required: false, description: 'Show the "differences only" filter toggle. Default true.' },
  },
  example: {
    type: 'comparison-layout',
    props: {
      title: 'Observability platforms',
      description: 'Compare Datadog, New Relic, and Grafana Cloud for production monitoring.',
      primaryLabel: 'Choose plan',
      items: [
        {
          id: 'datadog',
          title: 'Datadog',
          subtitle: 'Pro tier',
          price: '$15 / host / mo',
          image: 'https://example.com/datadog.png',
          ingestion: '15-day retention',
          apm: true,
          rum: true,
          sso: true,
          rating: 4,
          actions: [{ action: 'emit', target: 'chat.send', value: 'Tell me more about choosing Datadog.' }],
          learn_more: [{ action: 'navigate', url: 'https://datadoghq.com/pricing' }],
        },
        {
          id: 'newrelic',
          title: 'New Relic',
          subtitle: 'Standard',
          price: '$0.30 / GB',
          image: 'https://example.com/newrelic.png',
          ingestion: '8-day retention',
          apm: true,
          rum: true,
          sso: false,
          rating: 4,
          actions: [{ action: 'emit', target: 'chat.send', value: 'Tell me more about choosing New Relic.' }],
        },
        {
          id: 'grafana',
          title: 'Grafana Cloud',
          subtitle: 'Pro',
          price: '$8 / user / mo',
          image: 'https://example.com/grafana.png',
          ingestion: '13-month retention',
          apm: true,
          rum: false,
          sso: true,
          rating: 5,
          actions: [{ action: 'emit', target: 'chat.send', value: 'Tell me more about choosing Grafana Cloud.' }],
        },
      ],
      features: [
        { key: 'ingestion', label: 'Log retention', section: 'Data', highlight: true },
        { key: 'apm', label: 'APM tracing', section: 'Features', type: 'boolean', highlight: true },
        { key: 'rum', label: 'Real-user monitoring', section: 'Features', type: 'boolean' },
        { key: 'sso', label: 'SSO / SAML', section: 'Security', type: 'boolean' },
        { key: 'rating', label: 'G2 score', section: 'Reviews', type: 'rating' },
      ],
    },
  },
};
